### ISSUE TITLE
error en el cmake

### ISSUE THREAD

**Issue by remamakiller** [pangolp/cataclysm434#1]
Cmake 3.16 , me da error
compilando en vs 2019. 64 bits
Acá dejo el error del Cmake
https://mega.nz/#!t9IV3QIZ!lt5QWvoTipn0CBNzV2ihCy2re4iG8Z2f8lCnNEUQ2Xg

**Comment by pangolp** [comment]
La verdad es que no soy experto en cmake, pero si arrastras el error que te tira (es decir, la captura de la pantalla) acá al issue, lo carga como una imagen. Quizás en la imagen pueda deducir mejor cual es el problema. Si fuera Linux, te diría que ni idea porque aún no intente compilarlo en dicho sistema operativo, pero Windows, yo logre hacerlo. Aunque me parece que use el visual studio 14, es decir, el 2015. De todos modos, arrastra la imagen y vemos.

**Comment by pangolp** [comment]
También existe este otro proyecto sino: **https://github.com/gpn39f/ArkCORE-434**. Nose cual este mas avanzado realmente. Se puede trabajar en ambos, de hecho, yo trato de aportarle algunas cosas de vez en cuando.

**Comment by remamakiller** [comment]
Si lo compilé , pero DragonSoul  , está muy roto y es la mejor mazmorra de 4.3.4
Por rso estaba buscando algo mas nuevo
Esos guiones tienen 4 años

[url=https://postimages.org/][img]https://i.postimg.cc/sgcg4m6s/guiones.png[/img][/url][url=https://postimages.org/]how to host pictures online[/url]

**Comment by pangolp** [comment]
Si, pasa que no tiene desarrolladores, esta haciendo el trabajo el solo, es mas, le sacaron los permisos del repositorio original. Por eso tuvo que arrancar ese otro repositorio.
